import { Montserrat, Lato, Open_Sans } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  display: 'swap',
})

const lato = Lato({
  variable: '--font-lato',
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

const openSans = Open_Sans({
  variable: '--font-openSans',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Listed Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      className={`${montserrat.variable} ${lato.variable} ${openSans.variable}`}
    >
      <body>{children}</body>
    </html>
  )
}
